name: daily
on:
  # build every day at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  safety-check:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - uses: actions/setup-python@v2
    - name: install requirements
      run: python -m pip install tox
    - name: run safety check
      run: tox -e safety

